### ISSUE TITLE
Fungerar DivideByZero?

### ISSUE THREAD

**Issue by kentgoran** [kentgoran/VersionControlCalc#3]
Kan någon testa om det fungerar?

**Comment by kentgoran** [comment]
Assignade @narzuz

**Comment by narzuz** [comment]
Vet inte, lös de själv

**Comment by narzuz** [comment]
@kentgoran Maneten

**Comment by kentgoran** [comment]
- [ ] Assign Narzuz
- [ ] Make Narzuz fix shit
- [x] Cry in a corner

**Comment by narzuz** [comment]
slyyyta
